language: python
python:
  - 3.4
  - 3.5
  - 3.6
install: pip install tox
script:
  # Schema tests
  - tests/schemas/run.sh
  # Python binding tests
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
